# Prepare environment for scripts
- name: Prepare Environment for scripts - BDWATCHDOG_PATH
  lineinfile:
    path: /etc/environment
    line: "export BDWATCHDOG_PATH={{ bdwatchdog_path }}/"

- name: Prepare Environment for scripts - RESCALING_PATH
  lineinfile:
    path: /etc/environment
    line: "export RESCALING_PATH={{ serverless_containers_path }}/scripts/"

- name: Prepare Environment for scripts - PYTHONPATH
  lineinfile:
    path: /etc/environment
    line: "export PYTHONPATH=:{{ serverless_containers_path }}/scripts/"

# Starting Node Rescaler
- name: Tmux session check
  shell: tmux ls
  register: tmux_output
  ignore_errors: yes

- name: Starting Services - node scaler
  shell: bash scripts/services/node_scaler/start_tmux.sh
  when: "'node_scaler' not in tmux_output.stdout"
  args:
    chdir: "{{ serverless_containers_path }}"
    executable: /bin/bash

