# Define tasks here
- name: 1 - Install apache
  package:
    name: apache2
    state: latest
    
- name: 2 - Enable apache mod rewrite
  apache2_module:
    name: rewrite
    state: present    
  notify: Restart apache
    
- name: 3 - Delete apache default web server
  file:
    path: /etc/apache2/sites-enabled/{{ default_site }}
    state: absent
  notify: Restart apache
    
- name: 4 - Create apache web server directory
  file:
    path: /var/www/{{ http_host }}
    state: directory     
    mode: "0755"
    
- name: 5 - Copy index.html template
  template:
    src: templates/index.html.j2
    dest: /var/www/{{ http_host }}/index.html
  notify: Restart apache
    
- name: 6 - Copy apache.conf template
  template:
    src: templates/apache.conf.j2
    dest: /etc/apache2/sites-enabled/{{ http_conf }}
  notify: Restart apache