
- name: Copy apptainer containers definition file
  template:
    src: "templates/{{ definition_file }}"
    dest: "{{ installation_path }}/{{ definition_file }}"

- name: Copy apptainer containers cgroup config
  template:
    src: "templates/{{ cgroups_file }}"
    dest: "{{ installation_path }}/{{ cgroups_file }}"

- name: Build image
  shell: "singularity build {{ image_file }} {{ definition_file }}"
  args:
    chdir: "{{ installation_path }}"
    executable: /bin/bash
    creates: "{{ image_file }}"

- name: Check containers status
  shell: sudo singularity instance list -j
  register: apptainer_list_output
  args:
    executable: /bin/bash

- name: Start apptainer containers
  shell: "sudo singularity instance start -C --hostname {{ item }} --apply-cgroups {{ cgroups_file }} {{ image_file }} {{ item }}"
  when: "'\"instance\": \"{{ item }}\",' not in apptainer_list_output.stdout"
  args:
    chdir: "{{ installation_path }}"
    executable: /bin/bash
  loop: "{{ hostvars[inventory_hostname].containers }}"

## Fix to get the right permissions on cgroups files
- name: Copy cgroups v1 permission changer script
  copy:
    src: scripts/change_cgroupsv1_permissions.py
    dest: "{{ installation_path }}/change_cgroupsv1_permissions.py"

- name: Change cgroups v1 permissions
  shell: "python3 change_cgroupsv1_permissions.py singularity {{ item }}"
  args:
    chdir: "{{ installation_path }}"
    executable: /bin/bash
  loop: "{{ hostvars[inventory_hostname].containers }}"
