
## Initialize container limits on Node Recaler
- name: Initializing State Database - container cpu limit on Node Scaler
  shell: "python3 scripts/stateDatabase/init_host_node_rescaler_v2.py {{ item }} cpu {{ containers_info | replace(' ','') | quote }} config/config.yml"
  args:
    executable: /bin/bash
  with_items: "{{ nodes }}"

- name: Initializing State Database - container mem limit on Node Scaler
  shell: "python3 scripts/stateDatabase/init_host_node_rescaler_v2.py {{ item }} mem {{ containers_info | replace(' ','') | quote }} config/config.yml"
  args:
    executable: /bin/bash
  with_items: "{{ nodes }}"