
## Initialize container limits on Node Recaler
- name: Initializing State Database - container cpu limit on Node Scaler
  shell: "python3 scripts/stateDatabase/init_host_node_rescaler.py {{ item }} cpu {{ hostvars[item].cpu }} {{ hostvars[item].containers | replace('[','') | replace(']','') | replace(', ',',') }} config/config.yml"
  args:
    executable: /bin/bash
  with_items: "{{ groups['nodes'] }}"

- name: Initializing State Database - container mem limit on Node Scaler
  shell: "python3 scripts/stateDatabase/init_host_node_rescaler.py {{ item }} mem {{ hostvars[item].mem }} {{ hostvars[item].containers | replace('[','') | replace(']','') | replace(', ',',') }} config/config.yml"
  args:
    executable: /bin/bash
  with_items: "{{ groups['nodes'] }}"