
- name: Initializing State Database - container cpu and mem limits on Node Scaler
  shell: "{% for item in nodes %}python3 scripts/stateDatabase/init_host_node_rescaler_v3.py {{ item }} {{ containers_info | replace(' ','') | quote }} && {% endfor %}true"
  args:
    executable: /bin/bash
