
- name: Install prerequisites for Apptainer
  apt:
    name: 
     - build-essential
     - libseccomp-dev
     - pkg-config
     - uidmap
     - squashfs-tools
     - squashfuse
     - fuse2fs
     - fuse-overlayfs
     - fakeroot
     - cryptsetup
     - curl
     - wget
     - git
    state: latest  
    update_cache: yes

- name: Create Go executable symlink
  file:
    src: "{{ golang_install_dir }}/bin/go"
    dest: /usr/local/bin/go
    state: link   

- name: Clone Apptainer repo
  git:
    repo: https://github.com/apptainer/apptainer.git
    dest: "{{ apptainer_repo_path }}"

- name: Check for apptainer installation
  stat:
    path: "{{ apptainer_repo_path }}/builddir/apptainer"
  register: stat_output

- name: Configure Apptainer
  shell: ./mconfig
  when: not stat_output.stat.exists
  args:
     chdir: "{{ apptainer_repo_path }}"
     executable: /bin/bash

- name: Build Apptainer
  make: 
     chdir: "{{ apptainer_repo_path }}/builddir"
  when: not stat_output.stat.exists

- name: Install Apptainer
  become: yes
  make: 
     chdir: "{{ apptainer_repo_path }}/builddir"
     target: install
  when: not stat_output.stat.exists
  
- name: Change Apptainer repo dir owner
  file:
    path: "{{ apptainer_repo_path }}"
    state: directory
    owner: "{{ username_on_the_host.stdout_lines[0] }}"
    recurse: yes
