        
- name: Copy BDWatchdog
  copy:
    src: bdwatchdog/
    dest: /root/BDWatchdog
    
- name: Create a BDWatchdog data directory
  file:
    path: /root/BDWatchdog_data
    state: directory
    #mode: '0755'

- name: Install BDWatchdog
  shell: bash install.sh
  args:
    chdir: /root/BDWatchdog/deployment/
    executable: /bin/bash
    
## puede estar bien para asegurarse de que esten instalados?

#- name: Update apt packages
#  become: true
#  apt:
#    update_cache: yes
    
#- name: Install java
#  package:
#    name: openjdk-8-jdk
#    state: latest
 
#- name: Install pip
#  package:
#    name: python3-pip
#    state: latest
