    
- name: Install prerequisites
  package:
    name: 
     - curl
     - apt-transport-https
     - gnupg
    state: latest   
    
- name: Get repo key
  #shell: curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | tee /usr/share/keyrings/couchdb-archive-keyring.gpg >/dev/null 2>&1 
  apt_key:
    url: https://couchdb.apache.org/repo/keys.asc
    keyring: /usr/share/keyrings/couchdb-archive-keyring.gpg
    state: present
  
- name: Source os-release
  shell: source /etc/os-release 
  args:
     executable: /bin/bash
     
- name: Update sources.list
  shell: echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ focal main" | tee /etc/apt/sources.list.d/couchdb.list >/dev/null

- name: Update apt packages
  become: true
  apt:
    update_cache: yes   

- name: Populate service facts
  service_facts:

- name: Prepare non-interactive installation and install CouchDB
  when: "'couchdb' not in services"
  shell: debconf-copydb importmedb configdb  \
    --config=Name:importmedb               \
    --config=Driver:File                   \
    --config=Filename:config/debian_couchdb_conf.dat && \
    apt-get install -y couchdb
    
- name: Start couchdb
  become: true
  service: 
    name: couchdb 
    state: started    
