
- name: Copy service aliases and port configuration to ServerlessContainers dir
  template:
    src: templates/sc_services_config.yml
    dest: "{{ serverless_containers_path }}/services_config.yml"

- name: Copy service aliases and port configuration to BDWatchdog dir
  template:
    src: templates/bdw_services_config.yml
    dest: "{{ bdwatchdog_path }}/services_config.yml"