
- name: Install lxd
  package:
    name: lxd
    state: latest

## Install OpenSSL key with provided script
- name: Create OpenSSL key and certificate
  shell: bash scripts/lxd/create_lxd_key.sh
  args:
    chdir: "{{ serverless_containers_path }}"
    executable: /bin/bash
    creates: "{{ lxd_key_path }}/{{ lxd_key_name }}.crt"


## Add certificate to trust store
- name: Check if certificate already added to trust store
  shell: lxc config trust list -f csv | wc -l  
  register: lxc_trust_output
        
- name: Setup lxd (1)
  shell: "lxc config trust add {{ lxd_key_path }}/{{ lxd_key_name }}.crt"
  when: lxc_trust_output.stdout | int == 0
  args:
    executable: /bin/bash
    
- name: Setup lxd (2)
  shell: lxc config set core.https_address [::]:8443
  args:
    executable: /bin/bash
    
- name: Setup lxd (3)
  shell: lxc config set core.trust_password TRUE
  args:
    executable: /bin/bash

- name: Init lxd
  shell: lxd init --auto
  
