
- name: Install lxd
  package:
    name: lxd
    state: latest
  
# Install atop on host in order to get binary
- name: Install atop on host
  package: 
    name: atop
    state: latest

## A lo mejor no interesa pararlos por si estaban corriendo de normal
- name: Stop atop on host
  become: true
  service: 
    name: atop 
    state: stopped 

- name: Stop atopacct on host
  become: true
  service: 
    name: atopacct 
    state: stopped 