- name: Install pip3
  package:
    name: python3-pip
    state: latest

- name: Install pip dependencies
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - libtmux
    - ansible_runner