
- name: Install pip3
  package:
    name: python3-pip
    state: latest

- name: Check if ServerlessContainers directory is already there
  stat:
    path: /root/ServerlessContainers
  register: stat_output

- name: Copy ServerlessContainers
  when: not stat_output.stat.exists
  copy:
    src: ServerlessContainers/
    dest: /root/ServerlessContainers    
    
- name: Install specified python requirements
  pip:
    requirements: /root/ServerlessContainers/requirements.txt
    
- name: Install gunicorn
  package:
    name: gunicorn
    state: latest
