
- name: Install pip3
  when: "virtual_mode"
  package:
    name: python3-pip
    state: latest

- name: Install yq
  when: "virtual_mode"
  snap:
    name: yq
    state: present

- name: Check if ServerlessContainers directory is already there
  stat:
    path: "{{ serverless_containers_path }}"
  register: stat_output

## get the user executing the playbook
- name: get the username running the deploy
  become: no
  local_action: command whoami
  register: username_on_the_host

- name: Copy ServerlessContainers
  when: not stat_output.stat.exists
  copy:
    src: ServerlessContainers/
    dest: "{{ serverless_containers_path }}"
    owner: "{{ username_on_the_host.stdout_lines[0] }}"

- name: Install specified python requirements
  pip:
    requirements: "{{ serverless_containers_path }}/requirements.txt"
    executable: pip3

- name: Install gunicorn
  when: "virtual_mode"
  package:
    name: gunicorn
    state: latest

- name: Copy service aliases and port configuration to ServerlessContainers dir
  template:
    src: templates/sc_services_config.yml
    dest: "{{ serverless_containers_path }}/services_config.yml"