
- name: Install pip3
  package:
    name: python3-pip
    state: latest

- name: Copy ServerlessContainers
  copy:
    src: ServerlessContainers/
    dest: /root/ServerlessContainers    
    
- name: Install specified python requirements
  pip:
    requirements: /root/ServerlessContainers/requirements.txt
    
- name: Install gunicorn
  package:
    name: gunicorn
    state: latest
