
- name: Install pip3
  package:
    name: python3-pip
    state: latest

- name: Check if ServerlessContainers directory is already there
  stat:
    path: "{{ serverless_containers_path }}"
  register: stat_output

- name: Copy ServerlessContainers
  when: not stat_output.stat.exists
  copy:
    src: ServerlessContainers/
    dest: "{{ serverless_containers_path }}"
    
- name: Install specified python requirements
  pip:
    requirements: "{{ serverless_containers_path }}/requirements.txt"
    
- name: Install gunicorn
  package:
    name: gunicorn
    state: latest
