
- name: Install pip3
  package:
    name: python3-pip
    state: latest
    
- name: Install pip dependencies
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - Django
    - django-crispy-forms
    - beautifulsoup4

- name: Install yq
  snap:
    name: yq
    state: present

- name: Copy Django secret key file
  copy:
    src: config/secret_key.txt
    dest: /etc/secret_key.txt
