
- name: Prepare Environment for scripts - BDWATCHDOG_PATH
  lineinfile:
    path: /etc/environment
    line: export BDWATCHDOG_PATH=/root/BDWatchdog/

- name: Prepare Environment for scripts - RESCALING_PATH
  lineinfile:
    path: /etc/environment
    line: export RESCALING_PATH=/root/ServerlessContainers/scripts/

- name: Prepare Environment for scripts - PYTHONPATH
  lineinfile:
    path: /etc/environment
    line: export PYTHONPATH=:/root/ServerlessContainers/scripts/

# Starting Node Rescaler

- name: Tmux session check
  shell: tmux ls
  register: tmux_output
  ignore_errors: yes
  #no_log: True

- name: Starting Services - node rescaler
  shell: bash scripts/services/start_node_rescaler.sh 
  when: "'NodeRescaler' not in tmux_output.stdout"
  args:
    chdir: /root/ServerlessContainers
    executable: /bin/bash

