
- name: Tmux session check
  shell: tmux ls
  register: tmux_output
  ignore_errors: yes
  #no_log: True

- name: Starting Services - TIMESTAMPING Service
  shell: bash start.sh 
  when: "'EVE_TIMES' not in tmux_output.stdout"
  args:
    chdir: "{{ bdwatchdog_path }}/deployment/timestamps"
    executable: /bin/bash

- name: Starting Services - OPENTSDB
  shell: bash start.sh 
  when: "'OPENTSDB' not in tmux_output.stdout"
  args:
    chdir: "{{ bdwatchdog_path }}/deployment/metrics"
    executable: /bin/bash

- name: Starting Services - Web Server
  shell: bash start.sh 
  args:
    chdir: "{{ bdwatchdog_path }}/deployment/webviewer"
    executable: /bin/bash

- name: Copy Script for creating metrics
  copy:
    src: "{{ serverless_containers_path }}/scripts/databases/create-rescaler-opentsdb-metrics.sh"
    dest: "{{ bdwatchdog_path }}/deployment/metrics/opentsdb/create-rescaler-opentsdb-metrics.sh"
    remote_src: yes
    
- name: Run metrics script
  shell: bash create-rescaler-opentsdb-metrics.sh
  args:
    chdir: "{{ bdwatchdog_path }}/deployment/metrics/opentsdb/"
    executable: /bin/bash
