
- name: Tmux session check
  shell: tmux ls
  register: tmux_output
  ignore_errors: yes
  tags: restart_services

- name: Starting Services - Web Interface
  shell: "bash start_tmux.sh {{ web_interface_port }}"
  when: "'web_interface' not in tmux_output.stdout"
  args:
    chdir: "{{ web_interface_path }}"
    executable: /bin/bash
  tags: restart_services
