# Setup server
- name: Install requisites in server node
  hosts: localhost
  become: yes
  gather_facts: no

  vars_files:
    - vars/main.yml
    - config/config.yml
    
  environment: 
    HOME: /home/vagrant

  tasks:
    - import_tasks: tasks/install/couchdb_setup.yml
    - import_tasks: tasks/install/bdwatchdog_setup.yml
    - import_tasks: tasks/install/serverless_containers_setup.yml
    - import_tasks: tasks/install/hosts_setup_server.yml
    #- import_tasks: tasks/install/web_interface_setup.yml
    #- import_tasks: tasks/install/other_services_setup.yml
    - import_tasks: tasks/install/autoserverlessweb_services_setup.yml
    #- import_tasks: tasks/install/environment_setup.yml
    
# Setup nodes
- name: Install requisites in client nodes
  hosts: nodes
  become: yes
  gather_facts: yes

  vars_files:
    - vars/main.yml
    - config/config.yml

  environment:
    HOME: /home/vagrant

  roles:
     - role: gantsign.golang

  tasks:
    - import_tasks: tasks/install/serverless_containers_setup.yml
    - import_tasks: tasks/install/metrics_feeder_setup.yml
    - import_tasks: tasks/install/hosts_setup_nodes.yml
    #- import_tasks: tasks/install/environment_setup.yml

    - import_tasks: tasks/install/lxd_setup.yml
      when: "container_engine == 'lxc'"

    - import_tasks: tasks/install/apptainer_setup.yml
      when: "container_engine == 'apptainer'"