# Setup server
- hosts: localhost
  become: yes
  gather_facts: no

  vars_files:
    - vars/main.yml

  handlers:
    - import_tasks: handlers/main.yml
  tasks:
    - import_tasks: tasks/install/couchdb_setup.yml
    - import_tasks: tasks/install/bdwatchdog_setup.yml
    - import_tasks: tasks/install/serverless_containers_setup.yml
    - import_tasks: tasks/install/hosts_setup_server.yml
    - import_tasks: tasks/install/web_interface_setup.yml

    
# Setup nodes
- hosts: nodes
  become: yes
  gather_facts: yes

  vars_files:
    - vars/main.yml

  vars:
    - lxd_key_name: "lxd-{{ ansible_hostname }}"

  handlers:
    - import_tasks: handlers/main.yml
  tasks:
    - import_tasks: tasks/install/serverless_containers_setup.yml
    - import_tasks: tasks/install/lxd_setup.yml
    - import_tasks: tasks/install/metrics_feeder_setup.yml
    - import_tasks: tasks/install/hosts_setup_nodes.yml
    
