# Setup server
- name: Install requisites in server node
  hosts: localhost
  become: "{{ virtual_mode }}"
  gather_facts: no

  vars_files:
    - vars/main.yml
    - config/config.yml

  environment:
    HOME: "{{ lookup('env', 'HOME' )}}"
    INSTALLATION_PATH: "{{ installation_path }}"
    OPENTSDB_LOG_PATH: "{{ opentsdb_log_path | quote}}"

  tasks:
    - import_tasks: tasks/install/create_installation_dir.yml
    - import_tasks: tasks/install/couchdb_setup.yml
      when: "virtual_mode"

    - import_tasks: tasks/install/bdwatchdog_setup.yml
    - import_tasks: tasks/install/serverless_containers_setup.yml
    - import_tasks: tasks/install/hosts_setup.yml
    - import_tasks: tasks/install/autoserverlessweb_services_setup.yml
    - import_tasks: tasks/install/apptainer_setup.yml
      when: "virtual_mode and container_engine == 'apptainer'"

# Setup nodes
- name: Install requisites in client nodes
  hosts: nodes
  become: "{{ virtual_mode }}"
  gather_facts: yes

  vars_files:
    - vars/main.yml
    - config/config.yml

  environment:
    HOME: "{{ lookup('env', 'HOME' )}}"
    INSTALLATION_PATH: "{{ installation_path }}"

  tasks:
    - import_tasks: tasks/install/create_installation_dir.yml
    - import_tasks: tasks/install/serverless_containers_setup.yml
    - import_tasks: tasks/install/metrics_feeder_setup.yml # can be removed if an LXC container image is created
      when: "container_engine == 'lxc'"

    - import_tasks: tasks/install/hosts_setup.yml

    - import_tasks: tasks/install/lxd_setup.yml
      when: "virtual_mode and container_engine == 'lxc'"

    - import_tasks: tasks/install/apptainer_setup.yml
      when: "virtual_mode and container_engine == 'apptainer'"

    - import_tasks: tasks/install/network_setup.yml
      when: "container_engine == 'apptainer'"