# Setup server
- hosts: localhost
  become: yes
  gather_facts: no

  vars_files:
    - vars/main.yml
    - vars/django_key.yml

  environment:
    SECRET_KEY: "{{ DJANGO_SECRET_KEY }}"

  handlers:
    - import_tasks: handlers/main.yml
  tasks:
    - import_tasks: tasks/launch/couchdb_launch.yml
    - import_tasks: tasks/launch/opentsdb_setup.yml
    - import_tasks: tasks/launch/serverless_containers_launch.yml
    - import_tasks: tasks/launch/web_interface_launch.yml
    
# Setup nodes
- hosts: nodes
  become: yes
  gather_facts: no

  vars_files:
    - vars/main.yml

  #environment:
    #LXD_KEY_PATH: "{{ lxd_key_path }}"
    #LXD_KEY_NAME: "{{ lxd_key_name }}"
    #BDWATCHDOG_PATH: /root/BDWatchdog/
    #RESCALING_PATH: /root/ServerlessContainers/scripts/
    #PYTHONPATH: /root/BDWatchdog/:/root/ServerlessContainers/scripts/

  handlers:
    - import_tasks: handlers/main.yml
  tasks:
    - import_tasks: tasks/launch/node_rescaler_launch.yml
