# Setup server
- hosts: localhost
  become: yes
  gather_facts: no

  vars_files:
    - vars/main.yml
    - config/config.yml

  handlers:
    - import_tasks: handlers/main.yml
  tasks:
    - import_tasks: tasks/launch/couchdb_launch.yml
    - import_tasks: tasks/launch/opentsdb_setup.yml
    - import_tasks: tasks/launch/serverless_containers_launch.yml
    - import_tasks: tasks/launch/web_interface_launch.yml
    
