# Setup server
- hosts: localhost
  become: yes
  gather_facts: no

  vars_files:
    - vars/main.yml
    - config/config.yml

  vars:
    # change admin password both here and in config/debian_couchdb_conf.dat to effectively change it
    - couchdb_admin_pass: admin

  tasks:
    - import_tasks: tasks/launch/couchdb_launch.yml
    - import_tasks: tasks/launch/opentsdb_setup.yml
    - import_tasks: tasks/launch/serverless_containers_launch.yml
    - import_tasks: tasks/launch/web_interface_launch.yml
    
