# Setup nodes
- hosts: nodes
  become: no
  gather_facts: yes

  vars_files:
    - vars/main.yml
    - config/config.yml

  vars:
    - lxd_key_name: "lxd-{{ ansible_hostname }}"

  environment:
    BDWATCHDOG_PATH: "{{ bdwatchdog_path }}"
    RESCALING_PATH: "{{ serverless_containers_path }}/scripts/"
    PYTHONPATH: ":{{ serverless_containers_path }}"

  tasks:
    - import_tasks: tasks/lxd_setup/lxd_containers_setup.yml
      tags: start_containers
    - import_tasks: tasks/lxd_setup/node_rescaler_launch.yml

# Setup server (now that nodes have been initialized)
- hosts: localhost
  become: no
  gather_facts: no

  vars_files:
    - vars/main.yml
    - config/config.yml

  tasks:
    - import_tasks: tasks/lxd_setup/node_rescaler_containers_init.yml
      tags: start_containers