# Setup nodes
- hosts: nodes
  become: yes
  gather_facts: no

  vars_files:
    - vars/main.yml
    - config/config.yml

  tasks:
    - import_tasks: tasks/lxd_setup/lxd_containers_setup.yml
    - import_tasks: tasks/lxd_setup/node_rescaler_launch.yml

# Setup server (now that nodes have been initialized)
- hosts: localhost
  become: yes
  gather_facts: no

  vars_files:
    - vars/main.yml
    - config/config.yml

  tasks:
    - import_tasks: tasks/lxd_setup/node_rescaler_containers_init.yml