# Setup nodes
- hosts: nodes
  become: yes
  gather_facts: no

  vars_files:
    - vars/main.yml
    
  handlers:
    - import_tasks: handlers/main.yml
  tasks:
    - import_tasks: tasks/lxd_setup/lxd_containers_setup.yml
