# Setup nodes
- name: Start containers in client nodes
  hosts: nodes
  become: no
  gather_facts: no

  vars_files:
    - vars/main.yml
    - config/config.yml

  environment:
    BDWATCHDOG_PATH: "{{ bdwatchdog_path }}"
    SERVERLESS_PATH: "{{ serverless_containers_path }}"
    PYTHONPATH: "{{ bdwatchdog_path }}:{{ serverless_containers_path }}"

  tasks:
    - import_tasks: tasks/containers_setup/lxd_containers_setup.yml
      when: "container_engine == 'lxc'"
      tags: start_containers
      vars:
        - lxd_key_name: "lxd-{{ inventory_hostname }}"

    - import_tasks: "tasks/containers_setup/apptainer_containers_cgroups_{{ cgroups_version }}_setup.yml"
      when: "container_engine == 'apptainer'"
      tags: start_containers
      vars:
        - containers: "{{ container_list | split(',') if container_list is defined else hostvars[inventory_hostname].containers }}"
        - template_definition_file: "ubuntu_container.def"
        - definition_file: "ubuntu_container.def"
        - app_base_name: "base"
        - app_name: "{{ app_base_name }}"
        - app_base_image_file: "ubuntu_container.sif"
        - image_file: "{{ app_base_image_file }}"
        - cgroups_file: "apptainer_containers_cgroup.toml"
        - files_dir: ""
        - install_script: ""
        - bind_dir_on_container: /opt/bind

    - import_tasks: tasks/containers_setup/node_rescaler_launch.yml
      become: "{{ 'no' if container_engine == 'apptainer' else 'yes' }}"

# Setup server (now that nodes have been initialized)
- hosts: localhost
  become: no
  gather_facts: no

  vars_files:
    - vars/main.yml
    - config/config.yml

  environment:
    BDWATCHDOG_PATH: "{{ bdwatchdog_path }}"
    SERVERLESS_PATH: "{{ serverless_containers_path }}"
    PYTHONPATH: "{{ bdwatchdog_path }}:{{ serverless_containers_path }}"

  tasks:
    - import_tasks: tasks/containers_setup/node_rescaler_containers_init.yml
      tags: start_containers
      vars:
        - nodes: "{{ host_list | split(',') if host_list is defined else groups['nodes'] }}"