# Setup nodes
- name: Start containers in hosts
  hosts: nodes
  become: no
  gather_facts: no

  vars_files:
    - vars/main.yml
    - config/config.yml

  environment:
    BDWATCHDOG_PATH: "{{ bdwatchdog_path }}"
    SERVERLESS_PATH: "{{ serverless_containers_path }}"
    PYTHONPATH: "{{ bdwatchdog_path }}:{{ serverless_containers_path }}"

  tasks:
    - import_tasks: tasks/containers_setup/lxd_containers_setup.yml
      when: "container_engine == 'lxc'"
      tags: start_containers
      vars:
        - lxd_key_name: "lxd-{{ inventory_hostname }}"

    - import_tasks: "tasks/containers_setup/apptainer_containers_cgroups_{{ cgroups_version }}_setup.yml"
      when: "container_engine == 'apptainer'"
      vars:
        - files_dir: ""
        - install_script: ""
        - app_jar: ""
        - template_definition_file: "ubuntu_container.def"
        - definition_file: "{{ template_definition_file }}"
        - app_base_name: "{{ app_name if install_script != '' else 'hadoop' if app_jar != '' else 'base' }}"
        - app_name: "base"
        - app_base_image_file: "ubuntu_container.sif"
        - image_file: "{{ app_base_image_file }}"
        - cgroups_file: "apptainer_containers_cgroup.toml"
        - containers_info_str: >
              {%- set containers_info=[] -%}
              {%- for host in groups['nodes'] -%}
                {%- for container_name in hostvars[host].containers -%}
                  {%- set container_info = dict() -%}
                    {{ container_info.update({'container_name': container_name, 'host': host, 'cpu_max': max_cpu_percentage_per_container, 'cpu_min': min_cpu_percentage_per_container, 'mem_max': max_memory_per_container, 'mem_min': min_memory_per_container }) }}
                    {%- if hostvars[host].disks|length > 0 -%}
                      {%- if create_lvm -%}
                        {{ container_info.update( {'disk': 'lvm', 'disk_path': hostvars[host].disks['lvm']} ) }}
                      {%- else -%}
                        {%- set first_disk = hostvars[host].disks | first -%}
                        {{ container_info.update( {'disk': first_disk, 'disk_path': hostvars[host].disks[first_disk]} ) }}
                      {%- endif -%}
                    {%- endif -%}
                    {{ containers_info.append(container_info) }}
                {%- endfor -%}
              {%- endfor -%}
              {{ containers_info }}
        - containers_info: "{{ containers_info_str | replace('\n','') | replace(' ','') }}"

    - import_tasks: tasks/containers_setup/node_rescaler_launch.yml
      become: "{{ 'no' if container_engine == 'apptainer' else 'yes' }}"

# Setup server (now that nodes have been initialized)
- hosts: localhost
  become: no
  gather_facts: no

  vars_files:
    - vars/main.yml
    - config/config.yml

  environment:
    BDWATCHDOG_PATH: "{{ bdwatchdog_path }}"
    SERVERLESS_PATH: "{{ serverless_containers_path }}"
    PYTHONPATH: "{{ bdwatchdog_path }}:{{ serverless_containers_path }}"

  tasks:
    - import_tasks: tasks/containers_setup/node_rescaler_containers_init.yml
      tags: start_containers
      vars:
        - nodes: "{{ host_list | split(',') if host_list is defined else groups['nodes'] }}"
        - containers_info_str: >
              {%- set containers_info=[] -%}
              {%- for host in nodes -%}
                {%- for container_name in hostvars[host].containers -%}
                  {%- set container_info = dict() -%}
                    {{ container_info.update({'container_name': container_name, 'host': host, 'cpu_max': max_cpu_percentage_per_container, 'cpu_min': min_cpu_percentage_per_container, 'mem_max': max_memory_per_container, 'mem_min': min_memory_per_container }) }}
                    {{ containers_info.append(container_info) }}
                {%- endfor -%}
              {%- endfor -%}
              {{ containers_info }}
        - containers_info: "{{ containers_info_str | replace('\n','') | replace(' ','') }}"